(define (problem log-problem-1)
  (:domain log-problem)
  (:objects truck package1 tampinese changi bedok)
  (:init (truck truck) (package package1)    
          (location tampinese) (location changi) (location bedok)
          (at-truck truck tampinese)
          (at-package package1 bedok)
          (path tampinese changi) (path changi tampinese) (path changi bedok)
          (path bedok changi) (path tampinese bedok) (path bedok tampinese))

  (:goal (and (at-package package1 changi))))